### ISSUE TITLE
Multi-variable problem and multi-variable boundary condition 

### ISSUE THREAD

**Issue by adelerth** [ehsankharazmi/hp-VPINNs#2]
Hi!

I wish to contact you to ask a question about the VPINNs that I am trying to adapt for another problem.

In my problem, I have one pressure variable and two velocity variables both expressed with complex numbers. To work with these complex variables, I consider their real part and their imaginary part, which in the end means that I consider six variables in total. 
Moreover, one of the boundary conditions is expressed as a dependency between several of the problem variables. Do you believe that the VPINNs model can address this problem? 

Finally, I wish to take this opportunity to ask you if there is a way to take into account complex variables other than separating the real and imaginary parts ? 

Best, 

Theo

**Comment by ehsankharazmi** [comment]
Hi Theo,
VPINNs are able to handle multi-variable problems and there should not be any issue having six variables as long as your set of PDEs are identifiable. Note that since the boundary conditions are added as an extra term in the loss function, you can consider parametric boundary conditions. 
Regarding the complex variables, I am not aware of any method but separating it into the real and imaginary parts. 

Hope this helps.
Best,
Ehsan

**Comment by adelerth** [comment]
Hi ! 
Many thanks for your kind reply, 
This gives me the answer to my questions, 
Best, 
Theo
